=== 4711Lab7/timetable/Data/timetable.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--must be in this order-->
<!ELEMENT timetable (timeslots, daysofweek, courses)>

<!ELEMENT timeslots (time)*>

<!ELEMENT time (class)*>
<!ATTLIST time
    start CDATA #REQUIRED
>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT class EMPTY>
<!ATTLIST class
    location CDATA #REQUIRED
    day (monday | tuesday | wednesday | thursday | friday) #REQUIRED
    course (blaw3600 | comp4711 | comp4560 | comp4735 | comp4941 | comp4945) #REQUIRED
    instructor CDATA #REQUIRED
    end CDATA #REQUIRED
    start CDATA #REQUIRED
>
<!--must be in this order-->
<!ELEMENT daysofweek (weekday)*>

<!ELEMENT weekday (class)*>
<!ATTLIST weekday
     day (monday | tuesday | wednesday | thursday | friday) #REQUIRED
>

<!ELEMENT courses (course)*>

<!ELEMENT course (class)*>
<!ATTLIST course
    name CDATA #REQUIRED
>

=== 4711Lab7/timetable/Data/timetable.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE timetable SYSTEM "timetable.dtd">

<timetable>
    <timeslots>
        <time start="830">
            <class start="830" end="1020" instructor="Brenda Fine" course="comp4560" day="monday" location="se12-320"></class>
            <class start="830" end="1020" instructor="Catherine Ryan" course="blaw3600" day="friday" location="sw5-1840"></class>
        </time>
        <time start="930">
            <class start="930" end="1020" instructor="Tejinder Randhawa" course="comp4945" day="wednesday" location="se12-319"></class>
            <class start="930" end="1120" instructor="Catherine Ryan" course="blaw3600" day="thursday" location="sw3-2620"></class>
        </time>
        <time start="1030">
            <class start="1030" end="1120" instructor="Tejinder Randhawa" course="comp4941" day="wednesday" location="se12-319"></class>
        </time>
        <time start="1130">
            <class start="1130" end="1220" instructor="Mirela Gutica" course="comp4735" day="monday" location="sw1-1205"></class>
            <class start="1130" end="1220" instructor="Brenda Fine" course="comp4560" day="tuesday" location="sw5-1850"></class>
            <class start="1130" end="1220" instructor="Mirela Gutica" course="comp4735" day="thursday" location="sw3-1710"></class>
        </time>
        <time start="1230">
            <class start="1230" end="1420" instructor="James Parry" course="comp4711" day="tuesday" location="se12-320"></class>
            <class start="1230" end="1320" instructor="Brenda Fine" course="comp4560" day="friday" location="sw3-1750"></class>
        </time>
        <time start="1330">
            <class start="1330" end="1420" instructor="Mirela Gutica" course="comp4735" day="wednesday" location="sw1-1205"></class>
            <class start="1330" end="1720" instructor="Tejinder Randhawa" course="comp4945" day="thursday" location="se12-319"></class>
            <class start="1330" end="1720" instructor="Tejinder Randhawa" course="comp4941" day="friday" location="se12-319"></class>
        </time>
        <time start="1430">
            <class start="1430" end="1520" instructor="James Parry" course="comp4711" day="tuesday" location="sw5-1840"></class>
        </time>
        <time start="1530">
            <class start="1530" end="1720" instructor="Mathew Linder" course="comp4735" day="monday" location="se12-322"></class>
        </time>
        <time start="1630">
        </time>
    </timeslots>
    
    <daysofweek>
        <weekday day="monday">
            <class start="830" end="1020" instructor="Brenda Fine" course="comp4560" day="monday" location="se12-320"></class>
            <class start="1130" end="1220" instructor="Mirela Gutica" course="comp4735" day="monday" location="sw1-1205"></class>
            <class start="1530" end="1720" instructor="Mathew Linder" course="comp4735" day="monday" location="se12-322"></class>
        </weekday>
        <weekday day="tuesday">
            <class start="1130" end="1220" instructor="Brenda Fine" course="comp4560" day="tuesday" location="sw5-1850"></class>
            <class start="1230" end="1420" instructor="James Parry" course="comp4711" day="tuesday" location="se12-320"></class>
            <class start="1430" end="1520" instructor="James Parry" course="comp4711" day="tuesday" location="sw5-1840"></class>
        </weekday>
        <weekday day='wednesday'>
            <class start="930" end="1020" instructor="Tejinder Randhawa" course="comp4945" day="wednesday" location="se12-319"></class>
            <class start="1030" end="1120" instructor="Tejinder Randhawa" course="comp4941" day="wednesday" location="se12-319"></class>
            <class start="1330" end="1420" instructor="Mirela Gutica" course="comp4735" day="wednesday" location="sw1-1205"></class>
        </weekday>
        <weekday day='thursday'>
            <class start="930" end="1120" instructor="Catherine Ryan" course="blaw3600" day="thursday" location="sw3-2620"></class>
            <class start="1130" end="1220" instructor="Mirela Gutica" course="comp4735" day="thursday" location="sw3-1710"></class>
            <class start="1330" end="1720" instructor="Tejinder Randhawa" course="comp4945" day="thursday" location="se12-319"></class>
        </weekday>
        <weekday day='friday'>
            <class start="830" end="1020" instructor="Catherine Ryan" course="blaw3600" day="friday" location="sw5-1840"></class>
            <class start="1230" end="1320" instructor="Brenda Fine" course="comp4560" day="friday" location="sw3-1750"></class>
            <class start="1330" end="1720" instructor="Tejinder Randhawa" course="comp4941" day="friday" location="se12-319"></class>
        </weekday>
    </daysofweek>
    
    <courses>
        <course name='blaw3600'>
            <class start="930" end="1120" instructor="Catherine Ryan" course="blaw3600" day="thursday" location="sw3-2620"></class>
            <class start="830" end="1020" instructor="Catherine Ryan" course="blaw3600" day="friday" location="sw5-1840"></class>
        </course>
         <course name='comp4711'>
            <class start="1230" end="1420" instructor="James Parry" course="comp4711" day="tuesday" location="se12-320"></class>
            <class start="1430" end="1520" instructor="James Parry" course="comp4711" day="tuesday" location="sw5-1840"></class>
        </course>
         <course name='comp4560'>
            <class start="830" end="1020" instructor="Brenda Fine" course="comp4560" day="monday" location="se12-320"></class>
            <class start="1130" end="1220" instructor="Brenda Fine" course="comp4560" day="tuesday" location="sw5-1850"></class>
            <class start="1230" end="1320" instructor="Brenda Fine" course="comp4560" day="friday" location="sw3-1750"></class>
        </course>
        <course name='comp4735'>
            <class start="1130" end="1220" instructor="Mirela Gutica" course="comp4735" day="monday" location="sw1-1205"></class>
            <class start="1530" end="1720" instructor="Mathew Linder" course="comp4735" day="monday" location="se12-322"></class>
            <class start="1330" end="1420" instructor="Mirela Gutica" course="comp4735" day="wednesday" location="sw1-1205"></class>
            <class start="1130" end="1220" instructor="Mirela Gutica" course="comp4735" day="thursday" location="sw3-1710"></class>
        </course>
        <course name='comp4941'>
            <class start="1030" end="1120" instructor="Tejinder Randhawa" course="comp4941" day="wednesday" location="se12-319"></class>
            <class start="1330" end="1720" instructor="Tejinder Randhawa" course="comp4941" day="friday" location="se12-319"></class>
        </course>
        <course name='comp4945'>
            <class start="930" end="1020" instructor="Tejinder Randhawa" course="comp4945" day="wednesday" location="se12-319"></class>
            <class start="1330" end="1720" instructor="Tejinder Randhawa" course="comp4941" day="friday" location="se12-319"></class>
        </course>
    </courses>
</timetable>
